### ISSUE TITLE
Demo project failed buld with compiler errors

### ISSUE THREAD

**Issue by skywinder** [exchangegroup/Dodo#1]
![screen shot 2015-07-06 at 16 56 13](https://cloud.githubusercontent.com/assets/3356474/8523785/f60e556e-23ff-11e5-82e1-d2febca22e9a.png)

**Comment by evgenyneu** [comment]
Hi. Are using the Swift 2.0 Dodo code in Xcode 6? If you are, either switch to Xcode 7 or setup the previous version of Dodo: https://github.com/exchangegroup/Dodo/wiki/Swift-1.2-setup

**Comment by skywinder** [comment]
Oops. My fault, sorry. I try to run it in Xcode 6.
 Just wondering, that you put in `master` branch code that's not compatible with production code (since you can't release projects from beta version of Xcode).

So, in production I have to use version 1.0 right?

**Comment by evgenyneu** [comment]
@skywinder, yes, correct.
