### ISSUE TITLE
Adjust transparency?

### ISSUE THREAD

**Issue by timbroder** [exchangegroup/Dodo#10]
I'm having trouble making the bar more solid or transparent. 

Can you point me in the right direction? Thanks!

**Comment by evgenyneu** [comment]
Hi, @timbroder, thank you for the question. The transparency of the bar can be changed by setting the `view.dodo.style.bar.backgroundColor` and supplying a color with an alpha setting. For example:

``` Swift
view.dodo.style.bar.backgroundColor = UIColor.green().withAlphaComponent(0.2) 
```

Let me know if it works for you.

**Comment by evgenyneu** [comment]
Hi @timbroder, did you manage to change the transparency for the bar?

**Comment by evgenyneu** [comment]
Closing this issue, feel free to reopen if the needed.
