### ISSUE TITLE
Compile error with xcode 8 & swift 3

### ISSUE THREAD

**Issue by omidkh68** [exchangegroup/Dodo#11]
![screen shot 1395-07-12 at 23 51 37](https://cloud.githubusercontent.com/assets/4400137/19052648/6eeebb88-89c4-11e6-97e2-1ddba0e95dec.png)

I used Dodo v 7.0 instead of your documentation but during compilation that error occurred, How can I fix this problem?

**Comment by evgenyneu** [comment]
Hi @omidkh68, thanks for reporting. I assume your project is using Swift 3.0 (Build Settings > Use Legacy Swift Language version > No). I am sure you already done that, the first thing I would do is to clean the project, clear derived data/caches and restart Xcode 8.

Cleaning derived data and caches from console:

```
rm -rfd ~/Library/Developer/Xcode/DerivedData/*
rm -rfd ~/Library/Caches/com.apple.dt.Xcode/*
```

Sorry for this vague answer, I have not encountered this issue before. Let me know if you manage to fix this.

**Comment by evgenyneu** [comment]
@omidkh68,  does the problem still exist for you?

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
