### ISSUE TITLE
How to change horizontal margins?

### ISSUE THREAD

**Issue by RafaelPlantard** [exchangegroup/Dodo#12]
Is it possible edit margins?

**Comment by evgenyneu** [comment]
Hello @RafaelPlantard, thanks for the question.

One can change both horizontal and vertical margins between the Dodo message bar and its superview with the `style.bar.marginToSuperview` property. For example:

``` Swift
view.dodo.style.bar.marginToSuperview = CGSize(width: 50, height: 10)
```

<img width="375" alt="dodo_margins" src="https://cloud.githubusercontent.com/assets/880411/19404489/ff7416e6-92b9-11e6-9e6e-d9441528c400.png">

In addition, if you need to change the margin between the message bar label and the bar, there is another property that you can use:

``` Swift
view.dodo.style.label.horizontalMargin = 20
```

Is that what you were looking for?

**Comment by RafaelPlantard** [comment]
It's awesome thank you so much 👍
