### ISSUE TITLE
Hide method is working not properly

### ISSUE THREAD

**Issue by RafaelPlantard** [exchangegroup/Dodo#13]
Is very slow even with no animation. How can I fix it?
In Xcode 8.

**Comment by evgenyneu** [comment]
Hello @RafaelPlantard, thanks for reporting. 

I created a demo app that shows and hides the Dodo message in Xcode 8 and iOS 10 simulator and could not reproduce your problem. Maybe there is something else that influences the hiding of the message in your program?

Here is the demo project: 
[HideDodoDemo.zip](https://github.com/marketplacer/Dodo/files/530555/HideDodoDemo.zip)

<img width="373" alt="dodo_hide_demo" src="https://cloud.githubusercontent.com/assets/880411/19404589/07b461c0-92bb-11e6-803b-2148c9b3c053.png">

**Comment by RafaelPlantard** [comment]
I'm using RxSwift, maybe there is something related with the thread instance. I would try your sample code.
