### ISSUE TITLE
How to give custom location of view 

### ISSUE THREAD

**Issue by Shahbaz-Akram** [exchangegroup/Dodo#16]
I want to show view bottom of navigation bar how to handle it?

**Comment by evgenyneu** [comment]
Hi, did you try settings:

```
view.dodo.bottomLayoutGuide = bottomLayoutGuide
```

?

**Comment by evgenyneu** [comment]
@Shahbaz-Akram do you still have the issue?

**Comment by Shahbaz-Akram** [comment]
Resolved by adding new view.

**Comment by thakurkrishna1991** [comment]
Hi I am new to swift can you please elaborate what exactly I need to do with view.dodo.bottomLayoutGuide = bottomLayoutGuide 

what is bottomLayoutGuide if I am using tabbar in my view
I want my dodo view in bottom but it should not hide beneath to tabbar.
Thanks

**Comment by evgenyneu** [comment]
Hi @thakurkrishna1991, good question. If you have a tab bar view controller, you can do this

```
view.dodo.style.bar.locationTop = false
view.dodo.bottomLayoutGuide = bottomLayoutGuide
view.dodo.success("Hello World")
``` 
Here is a simple demo with a tab bar:

[DodoDemo.zip](https://github.com/evgenyneu/Dodo/files/1373149/DodoDemo.zip)

Let me know how it goes :)

**Comment by thakurkrishna1991** [comment]
@evgenyneu Thank you so much for quick response and for a good library. Its working fine for me.

**Comment by evgenyneu** [comment]
I'm glad it helped :)
