### ISSUE TITLE
How can I show it a little above the keyboard?

### ISSUE THREAD

**Issue by tnylee** [exchangegroup/Dodo#19]
![AltText](https://snag.gy/3HLgjM.jpg)

It's currently showing below the navigation bar and its blocking the keyboard cursor. I'd like to show it a little above the keyboard.

Here's where I want Dodo to appear.

![AltText](https://snag.gy/keqQuh.jpg)

I tried the following:

```
view.dodo.style.bar.locationTop = false
view.dodo.bottomAnchor = titleTextView.bottomAnchor
```

Dodo just doesn't appear when I use the above code. What can I do to accomplish this?

Thanks!

* Library setup method: CocoaPods
* Version of the library: 11.0.2
* Xcode version: 9.2
* OS version: iOS 11

**Comment by evgenyneu** [comment]
Thanks for reporting. Can you try this please?

```Swift
view.dodo.style.bar.locationTop = false

if #available(iOS 11, *) {
    view.dodo.topAnchor = view.safeAreaLayoutGuide.topAnchor
    view.dodo.bottomAnchor = view.safeAreaLayoutGuide.bottomAnchor
} else {
    view.dodo.topAnchor = topLayoutGuide.bottomAnchor
    view.dodo.bottomAnchor = bottomLayoutGuide.topAnchor
}
```

**Comment by evgenyneu** [comment]
Another thing that could go wrong is that if you access `view.dodo` property **after** the keyboard is shown, it may not detect the keyboard correctly. If that's the case, I would suggest accessing `view.dodo` very early, in `viewDidLoad` for example. 

The dodo object is created the first time you access `view.dodo` and that's when it [starts listening](https://github.com/evgenyneu/Dodo/blob/master/Dodo/Dodo.swift#L56) for keyboard events.

**Comment by tnylee** [comment]
It's working now. Thanks!
