### ISSUE TITLE
Is there a way to handle tap on the message body

### ISSUE THREAD

**Issue by lostpupil** [exchangegroup/Dodo#3]
Awesome project, I noticed that this only handle tap on left or right. Is there a way to handle the body?

**Comment by evgenyneu** [comment]
Hi @lostpupil, great idea! I have added the `onTap` handler for the bar.

```Swift
view.dodo.style.bar.onTap = { /* Button tapped */ }
```

**Comment by lostpupil** [comment]
Thank you very much!
