### ISSUE TITLE
Name Confilct

### ISSUE THREAD

**Issue by lostpupil** [exchangegroup/Dodo#5]
https://github.com/MengTo/Spring
yo man!
I notice this repo use SpringAnimation either.

**Comment by evgenyneu** [comment]
Renamed to SpringAnimationCALayer. Thanks for reporting.

**Comment by evgenyneu** [comment]
Did it solve your issue, @lostpupil?

**Comment by lostpupil** [comment]
@evgenyneu yes, I have already renamed it. Thanks very much. Not a big problem, just let you know that.
