### ISSUE TITLE
Can Dodo be used from Objective-C?

### ISSUE THREAD

**Issue by alexandre-g** [exchangegroup/Dodo#7]
Can't figure it out.. If it cannot be as of now, can it be changed to support?

**Comment by evgenyneu** [comment]
Hi @alexandre-g, yes you can use Dodo from Objective-C. Here is how: https://github.com/marketplacer/Dodo/wiki/Using-Dodo-in-Objective-C-project

**Comment by alexandre-g** [comment]
@evgenyneu Thanks for adding the example! That's pretty much what I ended up doing before you replied.
I am new to swift, but from what I've read swift extensions can be used from Obj-C. How come not in this case?

P.S Я тoжe pуccкий и тoже из aвcтpaлии, только с гoлд кocтa )

**Comment by evgenyneu** [comment]
@alexandre-g I assume that Dodo classes are not visible in Objective-C because they do not use Objective-C types (like NSObject) and/or not marked with `@objc` attribute. I prefer using Swift types in Dodo library though.

Nice to meet a fellow Russian Australian here, @alexandre-g.

**Comment by alexandre-g** [comment]
@evgenyneu Ah, that makes sense. Issue closed I guess!
