### ISSUE TITLE
possible to use top of all view

### ISSUE THREAD

**Issue by muhasturk** [exchangegroup/Dodo#9]
I've used dodo in scene where inside tab bar controller, if dodo is triggered background another view, I would like to dodo message is should be visible on top wherever user on tab item.

**Comment by evgenyneu** [comment]
Hi, @muhasturk, could you attach a screenshot so I can understand the issue please?

**Comment by evgenyneu** [comment]
Hi @muhasturk, is your question still relevant?

**Comment by evgenyneu** [comment]
Closing the issue, feel free to reopen if needed.
